#!/bin/bash
echo "Updating PiSCES files from s3 bucket"
kubectl exec oms-shell -- /bin/bash -c "cd /tmp/ ; rm -rf pisces"
kubectl exec oms-shell -- /bin/bash -c "aws s3 cp s3://qed-prod/pisces /tmp/pisces --recursive"
kubectl exec oms-shell -- /bin/bash -c "cd /mnt/app-data ; mkdir cyano ; cd cyano ; rm -r *"
kubectl exec oms-shell -- /bin/bash -c "cp -rf /tmp/pisces/*  /mnt/app-data/pisces/"
kubectl exec oms-shell -- /bin/bash -c "aws s3 cp s3://qed-prod/database/pisces /tmp/database/pisces --recursive"
kubectl exec oms-shell -- /bin/bash -c "cd /mnt/postgres-pvolume; rm -r *"
kubectl exec oms-shell -- /bin/bash -c "cp -rf /tmp/database/pisces/*  /mnt/postgres-pvolume/"
echo "Completed updates from s3 bucket"
