#!/bin/bash
echo "Updating PiSCES files from s3 bucket"
kubectl exec deploy/oms-shell -- /bin/bash -c "cd /tmp/pisces ; rm -rf pisces"
kubectl exec deploy/oms-shell -- /bin/bash -c "aws s3 cp s3://qed-stg/pisces /tmp/pisces --recursive"
kubectl exec deploy/oms-shell -- /bin/bash -c "cd /mnt/app-data ; mkdir pisces ; cd pisces ; rm -r *"
kubectl exec deploy/oms-shell -- /bin/bash -c "cp -rf /tmp/pisces/*  /mnt/app-data/pisces/"
kubectl exec deploy/oms-shell -- /bin/bash -c "aws s3 cp s3://qed-stg/database/pisces /tmp/database/pisces --recursive"
kubectl exec deploy/oms-shell -- /bin/bash -c "cd /mnt/postgres-pvolume; rm -r *"
kubectl exec deploy/oms-shell -- /bin/bash -c "cp -rf /tmp/database/pisces/*  /mnt/postgres-pvolume/"
kubectl exec deploy/oms-shell -- /bin/bash -c "chmod -R 777 /mnt/postgres-pvolume/*" 
echo "Completed updates from s3 bucket"
