apiVersion: v1
kind: Service
metadata:
  name: pisces-postgres
  namespace: pisces-kube
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: pisces-postgres
  type: ClusterIP
