apiVersion: v1
kind: Service
metadata:
  name: pisces-nginx
  namespace: qed-45-stg
spec:
  type: ClusterIP
  selector:
    app: pisces-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
