apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pisces-django
  name: pisces-django
  namespace: qed-kube-dev
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
       app: pisces-django
  template:
    metadata:
      labels:
        app: pisces-django
    spec:
      hostname: pisces-django
      containers:
      - name: pisces-django
        image: ghcr.io/quanted/pisces_app:dev-k
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: pisces-config
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /src/pisces_app/collected_static
          name: collected-static
        - mountPath: /src/app-data/
          name: pisces-app-data
      restartPolicy: Always
      volumes:
      - name: collected-static
        persistentVolumeClaim:
          claimName: collected-static-pvolume-claim1
      - name: pisces-app-data
        persistentVolumeClaim:
          claimName: app-data-pvolume-claim1