apiVersion: v1
kind: Service
metadata:
  name: pisces-nginx
  namespace: qed-kube-dev
spec:
  type: NodePort
  selector:
    app: pisces-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

