#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: pisces-postgres-pvc
#  labels:
#    app: pisces-postgres-pvc
#spec:
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 5Gi
#  selector:
#    matchLabels:
#      release: "stable"
#      name: pisces-postgres-pv