apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pisces-postgres-pvc
  namespace: qed-45-stg
spec:
  accessModes:
    - ReadWriteMany
  volumeName: pisces-postgres-pv
  resources:
    requests:
      storage: 5Gi