apiVersion: v1
kind: ConfigMap
metadata:
  name: pisces-config
  namespace: qed-45-stg
  labels:
    app: pisces-config
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  IN_DOCKER: "True"
  DJANGO_SETTINGS_MODULE: "pisces_app.app.settings"
  DEBUG: "False"
  PGDATA: "/var/lib/postgresql/data/sql"
