apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pisces-postgres-pv-claim
  labels:
    app: pisces-postgres
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      release: "stable"
      name: pisces-postgres-pv