apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pisces-nginx
  name: pisces-nginx
  namespace: qed-45-stg
  annotations:
    app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
    app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
    eks.amazonaws.com/compute-type: fargate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pisces-nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pisces-nginx
    spec:
      containers:
      - image: registry.epa.gov/qed/pisces_kube/pisces_nginx:dev-gl
        imagePullPolicy: Always
        name: pisces-nginx
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 30
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /src/collected_static
          name: collected-static
      imagePullSecrets:
      - name: glcr-auth
      restartPolicy: Always
      volumes:
      - name: collected-static
        persistentVolumeClaim:
          claimName: collected-static-pvolume-claim1
