apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pisces-collected-static-pvc
  labels:
    app: pisces-collected-static
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      release: "stable"
      name: pisces-collected-static-pv