apiVersion: v1
kind: Service
metadata:
  name: pisces-django
  namespace: qed-45-stg
spec:
  type: ClusterIP
  selector:
    app: pisces-django
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
