apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pisces-postgres-pv-claim
  namespace: qed-kube-dev
  labels:
    app: pisces-postgres
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
