apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pisces-django
  name: pisces-django
  namespace: pisces-kube
    annotations:
      app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
      app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
      eks.amazonaws.com/compute-type: fargate
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
       app: pisces-django
  template:
    metadata:
      labels:
        app: pisces-django
    spec:
      hostname: pisces-django
      containers:
      - name: pisces-django
        image: registry.epa.gov/qed/pisces_kube/pisces_django:dev-gl
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: pisces-config
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
        - mountPath: /src/pisces_app/collected_static
          name: collected-static
      restartPolicy: Always
      volumes:
      - name: collected-static
        persistentVolumeClaim:
          claimName: collected-static-pvolume-claim1
