apiVersion: v1
kind: PersistentVolume
metadata:
  name: pisces-postgres-pv
  labels:
    type: local
    app: pisces-postgres-pv
spec:
  storageClassName: pisces-postgres-pv
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /D//data/pisces/postgres-mount