apiVersion: v1
kind: Service
metadata:
  name: pisces-nginx
spec:
  type: NodePort
  selector:
    app: pisces-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000

