apiVersion: v1
kind: PersistentVolume
metadata:
  name: pisces-collected-static-pv
  labels:
    type: local
    app: pisces-collected-static
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  storageClassName: pisces-collected-static
  hostPath:
    path: \D\\git\pisces_kube\collected_static
